---
- name: Configure MikroTik devices
  hosts: mikrotik
  gather_facts: false
  vars_files:
    - "../inventory/group_vars/secrets.yml"
    - "../inventory/group_vars/networks.yml"
    - "../inventory/group_vars/leases.yml"
    - "../inventory/group_vars/dns.yml"

  tasks:
    - name: Rename interfaces for lab simulation
      when: "'lab' in group_names"
      community.routeros.command:
        commands:
          - /interface set [ find name="ether1" ] name="sfp-sfpplus1"
          - /interface set [ find name="ether2" ] name="sfp-sfpplus2"
      ignore_errors: true

    - name: Configure identity
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: system identity
        find: {}
        values: "{{ routeros.system_identity }}"
      when: routeros.system_identity is defined

    - name: Configure interfaces
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: interface
        find:
          name: "{{ item.name }}"
        values: "{{ item }}"
      loop: "{{ routeros.interface | default([]) }}"

    - name: Configure bridges
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: interface bridge
        find:
          name: "{{ item.name }}"
        values: "{{ item }}"
      loop: "{{ routeros.bridge | default([]) }}"

    - name: Configure bridge ports
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: interface bridge port
        find:
          interface: "{{ item.interface }}"
        values: "{{ item }}"
      loop: "{{ routeros.bridge_port | default([]) }}"

    - name: Configure bridge VLANs
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: interface bridge vlan
        find:
          vlan-ids: "{{ item['vlan-ids'] }}"
        values: "{{ item }}"
      loop: "{{ routeros.bridge_vlan | default([]) }}"

    - name: Configure IP addresses
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: ip address
        find:
          address: "{{ item.address }}"
        values: "{{ item }}"
      loop: "{{ routeros.ip_address | default([]) }}"

    - name: Configure Static Routes
      community.routeros.api_find_and_modify:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        path: ip route
        find:
          dst-address: "{{ item['dst-address'] }}"
        values: "{{ item }}"
      loop: "{{ routeros.ip_route | default([]) }}"

- name: Configure SwOS devices
  hosts: mikrotik
  gather_facts: false
  tasks:
    - name: Apply SwOS configuration
      when: swos_config is defined
      swos:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        config: "{{ swos_config }}"
