[mikrotik:children]
lab
prod

[lab]
rb5009 ansible_host=clab-mikrotik-lab-rb5009
crs328 ansible_host=clab-mikrotik-lab-crs328
crs310 ansible_host=clab-mikrotik-lab-crs310

[prod]
# rb5009_prod ansible_host=192.168.1.1
# crs328_prod ansible_host=192.168.1.2
# crs310_prod ansible_host=192.168.1.3
