[mikrotik:children]
lab
prod

[lab]
router_lab ansible_host=clab-mikrotik-lab-rb5009
switch3_lab ansible_host=clab-mikrotik-lab-crs328
css318_lab ansible_host=clab-mikrotik-lab-css318

[prod]
router ansible_host=192.168.1.230
switch3 ansible_host=192.168.1.4
# css318 ansible_host=192.168.1.3
