---
network:
  dns_entries:
    - hostname: roci.lanquarden.com
      address: 192.168.1.10
    - hostname: adguard.lanquarden.com
      address: 192.168.1.16
    - hostname: syslog.lanquarden.com
      address: 192.168.1.18
    - hostname: mqtt.lanquarden.com
      address: 192.168.1.19
    - hostname: k.lanquarden.com
      address: 192.168.1.15
