mikrotik_user: ENC[AES256_GCM,data:QNfxSF8=,iv:LtqyGAk0TRcL4k/hF1xYM8SkoioLuyvFMfmsewJjNtU=,tag:rmHCdxuoXPIFOAQyUcthyg==,type:str]
mikrotik_pass: ENC[AES256_GCM,data:K8JxPynmSKEobH9uI9FV3g==,iv:n5wh9jwf64IG7R3gm2AbmObxKubd5/SCWltVWs6/fUw=,tag:cWsrR88tJyAZfEo0cQ/sJg==,type:str]
mikrotik_bootstrap_user: ENC[AES256_GCM,data:NK9OCEY=,iv:A6J3H+/sueLmBuQRjcPO55y8FZW8oH4GdtG0Uv1BapU=,tag:h4fm6w5RZM1bMsKgdy+CqA==,type:str]
mikrotik_bootstrap_pass: ""
pppoe_user: ENC[AES256_GCM,data:GyIbXLlXWqsU/9X8+IHggRNE1m4Za0Sp,iv:rNkLP/V3BFjucRZn7Odmf3bJDTBGEBBV9HBPrvqQfBw=,tag:695RpCLLR1MawzFUuRjcXA==,type:str]
pppoe_pass: ENC[AES256_GCM,data:HjmorynrNA==,iv:tIk4aI6a8Y2K3K9NLJs4lZhMegZ2sVB1+6EwToHcl0c=,tag:p3Ggfjo8PsIo3l0kZANz+g==,type:str]
sops:
    age:
        - recipient: age106eq6dp3vmecwxydjrh0449zv2ru7rp2wdn5u6u8vu7tv320t3jswfgg73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcFkxUnd5MnNkc3JucFJ1
            ZXlmckNTWmc4OHZ6dnZqYmVzbE1EbGw1cW5NCkx4eEtxRURjSU5YNWx4Tld3OXN4
            THJnMnZnNUFXNFdLZXBUelBBMXNRVFEKLS0tICs1alRHUm5reUIrTGhza1EzZEo3
            TElCaFB0Zm4yZnZHRnFjdE5Wazd2Y1EKlxs44LxYWOLpVyyM1Goq4BHsUELcJ+oj
            /5800IGHfh4opnAecAPRReuRokpNhO61rfBnzc8tnajgp6MNQRLQjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T18:58:30Z"
    mac: ENC[AES256_GCM,data:uXLRDWPqDJTy8L0m6DUixCHVpZt9u688nx/CVwoRSt0ESnoIXTlH7KVBiPSpmQ9z+W4KSGD/3P+GXvteUEi38mPwQTNwkFMK1gHoOdpBjERl9fgOgVp8+gbHzs+W1JQJXGBYEa0hqZcEa8pcJEQS93pW3M7VUUTLWGTtu5AJFZQ=,iv:PdLpvkLCCBmbIlXLEdtymoxUsbExGKlE/VLyQaTXw+A=,tag:L8J2lX7Z3wI50XPzgUrAqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
