mikrotik_user: ENC[AES256_GCM,data:QNfxSF8=,iv:LtqyGAk0TRcL4k/hF1xYM8SkoioLuyvFMfmsewJjNtU=,tag:rmHCdxuoXPIFOAQyUcthyg==,type:str]
mikrotik_pass: ENC[AES256_GCM,data:K8JxPynmSKEobH9uI9FV3g==,iv:n5wh9jwf64IG7R3gm2AbmObxKubd5/SCWltVWs6/fUw=,tag:cWsrR88tJyAZfEo0cQ/sJg==,type:str]
mikrotik_bootstrap_user: ENC[AES256_GCM,data:NK9OCEY=,iv:A6J3H+/sueLmBuQRjcPO55y8FZW8oH4GdtG0Uv1BapU=,tag:h4fm6w5RZM1bMsKgdy+CqA==,type:str]
mikrotik_bootstrap_pass: ""
sops:
    age:
        - recipient: age106eq6dp3vmecwxydjrh0449zv2ru7rp2wdn5u6u8vu7tv320t3jswfgg73
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcFkxUnd5MnNkc3JucFJ1
            ZXlmckNTWmc4OHZ6dnZqYmVzbE1EbGw1cW5NCkx4eEtxRURjSU5YNWx4Tld3OXN4
            THJnMnZnNUFXNFdLZXBUelBBMXNRVFEKLS0tICs1alRHUm5reUIrTGhza1EzZEo3
            TElCaFB0Zm4yZnZHRnFjdE5Wazd2Y1EKlxs44LxYWOLpVyyM1Goq4BHsUELcJ+oj
            /5800IGHfh4opnAecAPRReuRokpNhO61rfBnzc8tnajgp6MNQRLQjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T17:31:56Z"
    mac: ENC[AES256_GCM,data:4J1eMg9PFrMYCE07iCUTAjE3fefJtpcPFc5h8YKJeufv7Bd5H+/jRLoKab7rAqdRqyryEYMPpFFEE13Qp5ywUT5YnHHBLDLel2YNXxnYtUhLjE1V4tMzMHpPrZClPcroLznCMTHQeza4PCNSeGB3A+opNB5nR8udXDiZso1eOuc=,iv:AgMZy0NlUuJNpQi7/jgJOdtuh1rAh/x/1/8B0x8XcBo=,tag:2MAIr1a7te6CtNS5gcrU2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
