---
ansible_connection: network_cli
ansible_network_os: community.routeros.routeros
ansible_python_interpreter: "{{ playbook_dir }}/../../.venv/bin/python"
ansible_user: "{{ (lookup('community.sops.sops', inventory_dir + '/group_vars/secrets.sops.yml') | from_yaml).mikrotik_user }}"
ansible_password: "{{ (lookup('community.sops.sops', inventory_dir + '/group_vars/secrets.sops.yml') | from_yaml).mikrotik_pass }}"
