---
# Define port groups for easier maintenance
trunk_ports: [ether17, ether18, ether23, ether24]
not_access_ports: [ether1, ether2, ether3, ether4, ether5, ether6, ether7, ether8]

routeros:
  system_identity:
    name: switch3

  interface:
    - { name: ether1, comment: Doorbell }
    - { name: ether2, comment: "Cam livingroom" }
    - { name: ether3, comment: "Cam garden" }
    - { name: ether4, comment: "Cam porch" }
    - { name: ether5, comment: "Cam garage" }
    - { name: ether6, comment: "Cam entrance" }
    - { name: ether7, comment: "Cam front" }
    - { name: ether8, comment: "Cam office" }
    - { name: ether17, comment: ap-livingroom }
    - { name: ether18, comment: ap-office }
    - { name: ether19, comment: TV }
    - { name: ether23, comment: uplink-office-1 }
    - { name: ether24, comment: uplink-office-2 }

  bridge:
    - name: bridge
      vlan-filtering: true
      admin-mac: "DC:2C:6E:8D:87:85"
      auto-mac: false
      comment: defconf

  bridge_port:
    - { bridge: bridge, interface: ether1, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether2, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether3, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether4, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether5, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether6, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether7, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether8, pvid: 30, frame-types: admit-only-untagged-and-priority-tagged }
    - { bridge: bridge, interface: ether9 }
    - { bridge: bridge, interface: ether10 }
    - { bridge: bridge, interface: ether11 }
    - { bridge: bridge, interface: ether12 }
    - { bridge: bridge, interface: ether13 }
    - { bridge: bridge, interface: ether14 }
    - { bridge: bridge, interface: ether15 }
    - { bridge: bridge, interface: ether16 }
    - { bridge: bridge, interface: ether17 }
    - { bridge: bridge, interface: ether18 }
    - { bridge: bridge, interface: ether19 }
    - { bridge: bridge, interface: ether20 }
    - { bridge: bridge, interface: ether21 }
    - { bridge: bridge, interface: ether22 }
    - { bridge: bridge, interface: ether23 }
    - { bridge: bridge, interface: ether24 }
    - { bridge: bridge, interface: sfp-sfpplus1 }
    - { bridge: bridge, interface: sfp-sfpplus2 }
    - { bridge: bridge, interface: sfp-sfpplus3 }
    - { bridge: bridge, interface: sfp-sfpplus4 }

  bridge_vlan:
    - { bridge: bridge, vlan-ids: 20, tagged: "{{ trunk_ports | join(',') }}" }
    - { bridge: bridge, vlan-ids: 30, tagged: "{{ trunk_ports | join(',') }}", untagged: "{{ not_access_ports | join(',') }}" }
    - { bridge: bridge, vlan-ids: 100, tagged: "{{ trunk_ports | join(',') }}" }

  ip_address:
    - address: 192.168.1.4/24
      interface: bridge
      comment: Management IP

  ip_route:
    - dst-address: 0.0.0.0/0
      gateway: 192.168.1.1
